"""A2A (Agent2Agent) protocol v1.0: the data model, and the mapping to a Run.

What is here is everything about A2A that is *not* a transport: the protocol's
objects as validated models, the two HTTP bindings' envelopes and route
tables, version and extension negotiation, Agent Card construction and
signing, and the pure mapping from what a Psych Run is to what an A2A Task is.

What is not here is the server. DESIGN.md §1 refuses "an HTTP server, a route
table, or any transport", and A2A is a transport, so the routes live in
``examples/playground/backend/app/a2a`` where a consumer can read them and
copy them. The outbound client lives in ``psych_runtime.tools.a2a``, because from a
running agent's point of view another agent is a tool source.

**gRPC is deliberately not implemented.** The proto defines three bindings and
§5.2 lets an agent declare which it offers ("Agents MUST declare all supported
protocols in their AgentCard", not "must offer all three"). gRPC needs a gRPC
server and generated protobuf stubs; Psych's dependency floor is pydantic and
httpx, and its example platform is FastAPI over HTTP. The two HTTP bindings
are functionally complete per §5.1, and a card built here declares exactly the
two it serves. This is an omission with a reason, not a gap: adding gRPC is a
consumer's ``AgentInterface`` plus their own server, and the mapping in
``psych_runtime.a2a.mapping`` is the same either way.

Specification references throughout this package are to A2A v1.0, with data
objects taken from ``specification/a2a.proto``, which §1.4 makes normative
over every generated artifact.
"""

from __future__ import annotations

from psych_runtime.a2a.card import DEFAULT_MEDIA_TYPES, agent_card, skills_of
from psych_runtime.a2a.errors import (
    A2AError,
    ContentTypeNotSupportedError,
    ExtendedAgentCardNotConfiguredError,
    ExtensionSupportRequiredError,
    InternalError,
    InvalidAgentResponseError,
    InvalidParamsError,
    InvalidRequestError,
    JsonParseError,
    MethodNotFoundError,
    PushNotificationNotSupportedError,
    TaskNotCancelableError,
    TaskNotFoundError,
    UnsupportedOperationError,
    VersionNotSupportedError,
    jsonrpc_error_object,
    rpc_status_body,
)
from psych_runtime.a2a.jsonrpc import (
    METHOD_PARAMS,
    STREAMING_METHODS,
    A2AMethod,
    error_response,
    parse_body,
    parse_request,
    stream_frame,
    success_response,
)
from psych_runtime.a2a.mapping import (
    MessageIntent,
    ResolvedMessage,
    artifact_of,
    context_id_of,
    history_of,
    resolve_message,
    status_message_of,
    stream_events,
    task_of,
    task_state_of,
)
from psych_runtime.a2a.models import (
    A2A_MEDIA_TYPE,
    AGENT_CARD_WELL_KNOWN_PATH,
    INTERRUPTED_STATES,
    TERMINAL_STATES,
    AgentCapabilities,
    AgentCard,
    AgentCardSignature,
    AgentExtension,
    AgentInterface,
    AgentProvider,
    AgentSkill,
    APIKeySecurityScheme,
    Artifact,
    AuthenticationInfo,
    CancelTaskRequest,
    DeleteTaskPushNotificationConfigRequest,
    GetExtendedAgentCardRequest,
    GetTaskPushNotificationConfigRequest,
    GetTaskRequest,
    HTTPAuthSecurityScheme,
    ListTaskPushNotificationConfigsRequest,
    ListTaskPushNotificationConfigsResponse,
    ListTasksRequest,
    ListTasksResponse,
    Message,
    MutualTlsSecurityScheme,
    OAuth2SecurityScheme,
    OAuthFlows,
    OpenIdConnectSecurityScheme,
    Part,
    ProtocolBinding,
    Role,
    SecurityRequirement,
    SecurityScheme,
    SendMessageConfiguration,
    SendMessageRequest,
    SendMessageResponse,
    StreamResponse,
    StringList,
    SubscribeToTaskRequest,
    Task,
    TaskArtifactUpdateEvent,
    TaskPushNotificationConfig,
    TaskState,
    TaskStatus,
    TaskStatusUpdateEvent,
    wire_dict,
)
from psych_runtime.a2a.negotiation import (
    A2A_EXTENSIONS_HEADER,
    A2A_VERSION_HEADER,
    PROTOCOL_VERSION,
    negotiate_version,
    parse_extensions_header,
    require_declared_extensions,
)
from psych_runtime.a2a.push import push_body, push_headers
from psych_runtime.a2a.rest import REST_ROUTES, SSE_MEDIA_TYPE, error_body, sse_frame
from psych_runtime.a2a.signing import (
    CardSigner,
    CardVerifier,
    HmacCardSigner,
    SignatureVerificationError,
    canonicalize,
    card_payload,
    sign_card,
    verify_card,
)

__all__ = [
    "A2A_EXTENSIONS_HEADER",
    "A2A_MEDIA_TYPE",
    "A2A_VERSION_HEADER",
    "AGENT_CARD_WELL_KNOWN_PATH",
    "DEFAULT_MEDIA_TYPES",
    "INTERRUPTED_STATES",
    "METHOD_PARAMS",
    "PROTOCOL_VERSION",
    "REST_ROUTES",
    "SSE_MEDIA_TYPE",
    "STREAMING_METHODS",
    "TERMINAL_STATES",
    "A2AError",
    "A2AMethod",
    "APIKeySecurityScheme",
    "AgentCapabilities",
    "AgentCard",
    "AgentCardSignature",
    "AgentExtension",
    "AgentInterface",
    "AgentProvider",
    "AgentSkill",
    "Artifact",
    "AuthenticationInfo",
    "CancelTaskRequest",
    "CardSigner",
    "CardVerifier",
    "ContentTypeNotSupportedError",
    "DeleteTaskPushNotificationConfigRequest",
    "ExtendedAgentCardNotConfiguredError",
    "ExtensionSupportRequiredError",
    "GetExtendedAgentCardRequest",
    "GetTaskPushNotificationConfigRequest",
    "GetTaskRequest",
    "HTTPAuthSecurityScheme",
    "HmacCardSigner",
    "InternalError",
    "InvalidAgentResponseError",
    "InvalidParamsError",
    "InvalidRequestError",
    "JsonParseError",
    "ListTaskPushNotificationConfigsRequest",
    "ListTaskPushNotificationConfigsResponse",
    "ListTasksRequest",
    "ListTasksResponse",
    "Message",
    "MessageIntent",
    "MethodNotFoundError",
    "MutualTlsSecurityScheme",
    "OAuth2SecurityScheme",
    "OAuthFlows",
    "OpenIdConnectSecurityScheme",
    "Part",
    "ProtocolBinding",
    "PushNotificationNotSupportedError",
    "ResolvedMessage",
    "Role",
    "SecurityRequirement",
    "SecurityScheme",
    "SendMessageConfiguration",
    "SendMessageRequest",
    "SendMessageResponse",
    "SignatureVerificationError",
    "StreamResponse",
    "StringList",
    "SubscribeToTaskRequest",
    "Task",
    "TaskArtifactUpdateEvent",
    "TaskNotCancelableError",
    "TaskNotFoundError",
    "TaskPushNotificationConfig",
    "TaskState",
    "TaskStatus",
    "TaskStatusUpdateEvent",
    "UnsupportedOperationError",
    "VersionNotSupportedError",
    "agent_card",
    "artifact_of",
    "canonicalize",
    "card_payload",
    "context_id_of",
    "error_body",
    "error_response",
    "history_of",
    "jsonrpc_error_object",
    "negotiate_version",
    "parse_body",
    "parse_extensions_header",
    "parse_request",
    "push_body",
    "push_headers",
    "require_declared_extensions",
    "resolve_message",
    "rpc_status_body",
    "sign_card",
    "skills_of",
    "sse_frame",
    "status_message_of",
    "stream_events",
    "stream_frame",
    "success_response",
    "task_of",
    "task_state_of",
    "verify_card",
    "wire_dict",
]
