"""A browser-based ``AuthorizationRedirectPort`` for the playground.

``psych_runtime.tools.oauth`` has the whole ``authorization_code`` + PKCE flow --
building the authorization URL, the ``state`` and RFC 9207 issuer checks, the
token exchange, refresh. What it deliberately does not have is the one piece
that is not a library's to own (DESIGN.md §1): somewhere for the user's
browser to land. ``OAuthClient`` takes an ``AuthorizationRedirectPort`` and
calls it when it needs a human to approve something; this is the playground's
implementation of that port, and it is exactly the "consumer's own OAuth
callback endpoint" the port's docstring describes.

## The shape, and why it is not simply "open a browser"

``authorize()`` is called deep inside a Run (or a preset test), on the server,
possibly minutes before anyone looks at the UI. It cannot open a browser
itself and must not block a Worker forever waiting for one. So it:

1. registers a pending authorization under the ``state`` the client generated,
2. returns control to the event loop and waits on a future,
3. is resolved by ``GET /api/oauth/callback`` when the browser finally lands.

The UI polls ``GET /api/oauth/pending`` and offers the link. That indirection
is what lets a Run started from a script, or a preset tested from a terminal,
still be authorized by a person in a browser later.

## Why keyed on ``state``

``state`` is per-authorization and unguessable, generated by ``OAuthClient``
for this one request, so it is the only correlator that works when two
authorizations are in flight at once -- two tenants connecting to the same
server, say. Keying on the server URL instead would let one tenant's callback
complete another tenant's authorization, which is the credential-crossing
DESIGN.md §10.4 calls the mistake that ends the project.

``OAuthClient`` still performs the real ``state`` comparison itself against
the value it sent; this class only routes the callback to the right waiter.
The lookup here is a routing decision, not a security check, and is written
so that a callback with an unknown ``state`` is dropped rather than guessed at.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import UTC, datetime

from psych_runtime.core.scope import Scope
from psych_runtime.tools.oauth.redirect import AuthorizationCallback

__all__ = ["BrowserAuthorizationRedirect", "PendingAuthorization"]

_DEFAULT_TIMEOUT_SECONDS = 300.0
"""Long enough for a person to notice the prompt, switch to a browser, sign in
and consent; short enough that an abandoned authorization does not pin a
Worker's lease for the rest of the process's life. On expiry the waiter raises
and the Run fails with a real reason rather than hanging."""


@dataclass(frozen=True)
class PendingAuthorization:
    """One authorization waiting for a browser. Surfaced by
    ``GET /api/oauth/pending`` so the UI can offer the link."""

    state: str
    authorization_url: str
    tenant: str
    started_at: datetime


class BrowserAuthorizationRedirect:
    """``AuthorizationRedirectPort`` backed by this backend's own callback
    route. One instance per process, shared by every Run and every preset test.
    """

    def __init__(self, *, timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS) -> None:
        self._timeout = timeout_seconds
        self._waiters: dict[str, asyncio.Future[AuthorizationCallback]] = {}
        self._pending: dict[str, PendingAuthorization] = {}

    async def authorize(
        self, scope: Scope, *, authorization_url: str, state: str
    ) -> AuthorizationCallback:
        """Register the authorization and wait for the browser to come back.

        Raises:
            TimeoutError: nobody completed it within the timeout. Surfaced as
                a failed Run with that reason, which is the honest outcome --
                the alternative is a Worker holding a lease on a Run nobody
                intends to finish.
        """
        loop = asyncio.get_running_loop()
        future: asyncio.Future[AuthorizationCallback] = loop.create_future()
        self._waiters[state] = future
        self._pending[state] = PendingAuthorization(
            state=state,
            authorization_url=authorization_url,
            tenant=scope.tenant,
            started_at=datetime.now(UTC),
        )
        try:
            return await asyncio.wait_for(future, timeout=self._timeout)
        finally:
            # Both dropped on every exit -- success, timeout or cancellation.
            # A waiter left behind would leak the future, and a pending entry
            # left behind would keep offering a link that resolves nothing.
            self._waiters.pop(state, None)
            self._pending.pop(state, None)

    def resolve(self, callback: AuthorizationCallback) -> bool:
        """Hand a callback to whoever is waiting on its ``state``.

        Returns ``False`` when no one is -- an unknown, stale or replayed
        ``state``. The callback is dropped rather than matched to some other
        waiter: guessing here is how one authorization completes another.
        """
        if callback.state is None:
            return False
        future = self._waiters.get(callback.state)
        if future is None or future.done():
            return False
        future.set_result(callback)
        return True

    def pending(self) -> list[PendingAuthorization]:
        """Authorizations waiting for a browser, oldest first."""
        return sorted(self._pending.values(), key=lambda p: p.started_at)
